/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Initial_Timer.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-9.844, 0, 0.001]} rotation={[0, 1.496, 0]} scale={0.098}>
        <group position={[-5.321, 4.77, -4.591]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane017.geometry}
            material={materials['Brick Wall']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane017_1.geometry}
            material={materials['Concrete floor']}
          />
        </group>
        <group position={[-5.321, 4.77, 4.588]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane007.geometry}
            material={materials['Brick Wall']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane007_1.geometry}
            material={materials['Concrete floor']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.brick_partition001.geometry}
          material={materials['Brick Wall']}
          position={[-7.088, 4.245, 3.059]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.brick_partition002.geometry}
          material={materials['Brick Wall']}
          position={[-7.088, 4.245, -3.053]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.brick_partition003.geometry}
          material={materials['Brick Wall']}
          position={[-7.088, 4.245, -0.006]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.brick_partition004.geometry}
          material={materials['Brick Wall']}
          position={[-7.088, 0.259, 3.059]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.brick_partition005.geometry}
          material={materials['Brick Wall']}
          position={[-7.088, 0.259, -3.053]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.brick_partition006.geometry}
          material={materials['Brick Wall']}
          position={[-7.088, 0.259, -0.006]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.brick_partition007.geometry}
          material={materials['Brick Wall']}
          position={[-5.071, 0.253, -4.58]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.brick_partition008.geometry}
          material={materials['Brick Wall']}
          position={[-1.533, 0.253, -4.58]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.brick_partition009.geometry}
          material={materials['Brick Wall']}
          position={[1.997, 0.253, -4.58]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.brick_partition010.geometry}
          material={materials['Brick Wall']}
          position={[5.544, 0.253, -4.58]}
        />
        <group position={[-5.321, 0.784, 4.588]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane012.geometry}
            material={materials['Brick Wall']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane012_1.geometry}
            material={materials['Concrete floor']}
          />
        </group>
        <group position={[-5.321, 8.77, -4.591]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane016.geometry}
            material={materials['Brick Wall']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane016_1.geometry}
            material={materials['Concrete floor']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.brick_partition013.geometry}
          material={materials['Brick Wall']}
          position={[7.077, 0.259, -0.006]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.brick_partition014.geometry}
          material={materials['Brick Wall']}
          position={[7.077, 0.259, -3.053]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <group position={[-7.084, 8.784, 2.809]} rotation={[0, Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane013.geometry}
            material={materials['Brick Wall']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane013_1.geometry}
            material={materials['Concrete floor']}
          />
        </group>
        <group position={[-7.084, 8.784, -0.256]} rotation={[0, Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane013.geometry}
            material={materials['Brick Wall']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane013_1.geometry}
            material={materials['Concrete floor']}
          />
        </group>
        <group position={[-7.084, 8.784, -3.303]} rotation={[0, Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane013.geometry}
            material={materials['Brick Wall']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane013_1.geometry}
            material={materials['Concrete floor']}
          />
        </group>
        <group position={[7.067, 8.784, 2.809]} rotation={[0, Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane013.geometry}
            material={materials['Brick Wall']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane013_1.geometry}
            material={materials['Concrete floor']}
          />
        </group>
        <group position={[7.067, 8.784, -0.256]} rotation={[0, Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane013.geometry}
            material={materials['Brick Wall']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane013_1.geometry}
            material={materials['Concrete floor']}
          />
        </group>
        <group position={[7.067, 8.784, -3.303]} rotation={[0, Math.PI / 2, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane013.geometry}
            material={materials['Brick Wall']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane013_1.geometry}
            material={materials['Concrete floor']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.brick_partition021.geometry}
          material={materials['Brick Wall']}
          position={[7.077, 0.259, 3.05]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <group position={[-5.321, 8.775, 4.588]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane019.geometry}
            material={materials['Brick Wall']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane019_1.geometry}
            material={materials['Concrete floor']}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.concrete_column.geometry}
          material={materials['Concrete Panels 01']}
          position={[-7.085, 0.25, 4.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.concrete_column001.geometry}
          material={materials['Concrete Panels 01']}
          position={[-7.085, 4.25, 4.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.concrete_column002.geometry}
          material={materials['Concrete Panels 01']}
          position={[-7.085, 8.25, 4.583]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.steps001.geometry}
          material={materials['Concrete Panels 01']}
          position={[-2.998, 8.127, -1.511]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.steps002.geometry}
          material={materials['Concrete Panels 01']}
          position={[1.425, 4.125, 1.505]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.windows_frame.geometry}
          material={materials.Concrete}
          position={[-7.088, 4.245, -0.006]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.windows_frame001.geometry}
          material={materials.Concrete}
          position={[-7.088, 0.259, -0.006]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.windows_frame002.geometry}
          material={materials.Concrete}
          position={[7.077, 0.259, -0.006]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.windows_frame003.geometry}
          material={materials.Concrete}
          position={[7.077, 0.259, -3.053]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.windows_frame004.geometry}
          material={materials.Concrete}
          position={[7.077, 0.259, 3.05]}
          rotation={[0, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wood_boards.geometry}
          material={materials['Spruce wood']}
          position={[-7.45, 13.583, 2.738]}
          rotation={[0.481, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wood_boards001.geometry}
          material={materials['Spruce wood']}
          position={[-7.45, 12.25, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wood_boards002.geometry}
          material={materials['Spruce wood']}
          position={[-7.45, 12.25, 1.408]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wood_boards003.geometry}
          material={materials['Spruce wood']}
          position={[-4.353, 13.392, 2.783]}
          rotation={[-1.087, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wood_boards004.geometry}
          material={materials['Spruce wood']}
          position={[-4.353, 14.098, 1.429]}
          rotation={[-1.089, 1.571, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wood_boards005.geometry}
          material={materials['Spruce wood']}
          position={[0.001, 14.797, -0.001]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wood_boards006.geometry}
          material={materials['Spruce wood']}
          position={[-7.45, 12.25, 2.76]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wood_boards007.geometry}
          material={materials['Spruce wood']}
          position={[-4.358, 12.296, 4.787]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wood_boards008.geometry}
          material={materials['Spruce wood']}
          position={[-7.45, 14.008, 0.103]}
          rotation={[Math.PI, 0, 0]}
        />
        <group position={[1.853, 8.259, 1.352]} rotation={[0, -0.465, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wood_boards009.geometry}
            material={materials['Spruce wood']}
            position={[-0.577, 0.046, 0.209]}
            rotation={[0, -0.349, -Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wood_boards010.geometry}
            material={materials['Spruce wood']}
            position={[-0.309, 0.046, 0.205]}
            rotation={[0, -0.349, -Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wood_boards011.geometry}
            material={materials['Spruce wood']}
            position={[-0.13, 0.046, 0.358]}
            rotation={[0, -0.349, -Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wood_boards012.geometry}
            material={materials['Spruce wood']}
            position={[0.091, 0.046, 0.409]}
            rotation={[0, -0.349, -Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wood_boards013.geometry}
            material={materials['Spruce wood']}
            position={[0.307, 0.046, 0.517]}
            rotation={[0, -0.349, -Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wood_boards014.geometry}
            material={materials['Spruce wood']}
            position={[-0.601, 0.141, 0.142]}
            rotation={[0, -0.349, -Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wood_boards015.geometry}
            material={materials['Spruce wood']}
            position={[-0.333, 0.141, 0.137]}
            rotation={[0, -0.349, -Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wood_boards016.geometry}
            material={materials['Spruce wood']}
            position={[-0.154, 0.141, 0.29]}
            rotation={[0, -0.349, -Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wood_boards017.geometry}
            material={materials['Spruce wood']}
            position={[0.068, 0.141, 0.342]}
            rotation={[0, -0.349, -Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wood_boards018.geometry}
            material={materials['Spruce wood']}
            position={[0.284, 0.141, 0.449]}
            rotation={[0, -0.349, -Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wood_boards019.geometry}
            material={materials['Spruce wood']}
            position={[-0.511, 0.242, 0.147]}
            rotation={[0, -0.402, Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wood_boards020.geometry}
            material={materials['Spruce wood']}
            position={[-0.243, 0.242, 0.157]}
            rotation={[0, -0.402, -Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wood_boards021.geometry}
            material={materials['Spruce wood']}
            position={[-0.103, 0.242, 0.391]}
            rotation={[0, -0.402, -Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wood_boards022.geometry}
            material={materials['Spruce wood']}
            position={[0.167, 0.242, 0.332]}
            rotation={[0, -0.402, -Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wood_boards023.geometry}
            material={materials['Spruce wood']}
            position={[0.325, 0.242, 0.574]}
            rotation={[0, -0.402, -Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wood_boards024.geometry}
            material={materials['Spruce wood']}
            position={[-0.281, 0.338, 0.109]}
            rotation={[0, -0.257, -Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wood_boards025.geometry}
            material={materials['Spruce wood']}
            position={[-0.102, 0.338, 0.322]}
            rotation={[0, -0.257, -Math.PI / 2]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wood_boards026.geometry}
            material={materials['Spruce wood']}
            position={[0.15, 0.338, 0.223]}
            rotation={[0, -0.257, Math.PI / 2]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.сoncrete_floor.geometry}
          material={materials['Concrete Panels 01']}
          position={[-5.002, 0, 2.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.сoncrete_floor001.geometry}
          material={materials['Concrete Panels 01']}
          position={[-5.002, 4, 2.5]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.сoncrete_floor002.geometry}
          material={materials['Concrete Panels 01']}
          position={[-0.002, 8.125, 0]}
          rotation={[Math.PI, 0, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.сoncrete_floor003.geometry}
          material={materials['Concrete Panels 01']}
          position={[-5.002, 12, 2.5]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Arena.geometry}
        material={materials['Wrinkled paper']}
        position={[0, 0, 0.001]}
        scale={1.043}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Jon_Stick.geometry}
        material={materials['Oak Wood2']}
        position={[-8.955, 0, 0.001]}
        rotation={[0, 0, -Math.PI]}
        scale={[-0.026, -1, -0.026]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Jon_Body.geometry}
          material={materials.Jon_Body}
          position={[1.452, 0.691, -0.817]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[-92.579, -39.07, -2.379]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Jon_Left_Arm.geometry}
          material={materials.Jon_Left_Arm}
          position={[1.456, 0.69, -0.886]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[-92.579, -39.07, -2.379]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Jon_Left_Leg.geometry}
          material={materials.Jon_Left_Leg}
          position={[1.456, 0.715, -0.388]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[-92.579, -39.07, -2.379]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Jon_Right_Arm.geometry}
          material={materials.Jon_Right_Arm}
          position={[1.456, 0.69, -2.226]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[-92.579, -39.07, -2.379]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Jon_Right_Leg.geometry}
          material={materials.Jon_Right_Leg}
          position={[1.456, 0.703, -1.679]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[-92.579, -39.07, -2.379]}
        />
      </mesh>
      <group position={[-9.88, 0, -1.727]} scale={0.046}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Small_Crane_Base.geometry}
          material={materials['Small Circle Crane. Disk Base']}
          position={[0, 0.405, 0]}>
          <group position={[0, 3.196, 0]} rotation={[Math.PI / 2, 0, Math.PI]}>
            <group position={[0, 0, 2.67]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube001.geometry}
                material={materials['Small Circle Crane_Body']}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube001_1.geometry}
                material={materials['Small Circle Crane Wheel']}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube001_2.geometry}
                material={materials['Small Crane Wire']}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube001_3.geometry}
                material={materials['Small Circle Crane. Window']}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube001_4.geometry}
                material={materials['Small Crane Generic Metal']}
              />
              <group position={[0.082, 2.348, -6.515]} rotation={[0, 1.571, 0]}>
                <group position={[0, -0.072, 4.205]} rotation={[0, -1.571, 0]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube3807.geometry}
                    material={materials['Small Circle Crane. Arm']}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube3807_1.geometry}
                    material={materials['Small Crane Wire']}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube3807_2.geometry}
                    material={materials['Small Crane Generic Metal']}
                  />
                  <group position={[-4.304, 49.789, -2.956]} rotation={[0, 1.571, 0]}>
                    <group position={[0, 0, 1.844]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder032.geometry}
                        material={materials['Small Circle Crane. Arm']}
                      />
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder032_1.geometry}
                        material={materials['Small Crane Generic Metal']}
                      />
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder032_2.geometry}
                        material={materials['Small Crane Wire']}
                      />
                    </group>
                    <group position={[0.016, -3.751, -6.299]} rotation={[-Math.PI, 1.571, 0]}>
                      <group position={[6.307, 4.05, 0]} rotation={[Math.PI, 0, 0]}>
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes.Cube.geometry}
                          material={materials['Small Circle Crane. Yellow']}
                        />
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes.Cube_1.geometry}
                          material={materials['Small Crane Generic Metal']}
                        />
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes.Cube_2.geometry}
                          material={materials['Small Crane Wire']}
                        />
                      </group>
                    </group>
                  </group>
                  <group position={[-4.307, 52.615, -0.588]} rotation={[0, Math.PI / 2, 0]}>
                    <group rotation={[0, -Math.PI / 2, 0]}>
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube3840.geometry}
                        material={materials['Small Circle Crane. Little Arm']}
                      />
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube3840_1.geometry}
                        material={materials['Small Crane Generic Metal']}
                      />
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube3840_2.geometry}
                        material={materials['Small Crane Wire']}
                      />
                      <group position={[0.001, -0.561, -13.802]} rotation={[0, 1.571, 0]}>
                        <group position={[0, -3.993, -1.94]} rotation={[-Math.PI, 1.571, 0]}>
                          <group position={[1.94, 0, 0]} rotation={[0, -0.004, -1.571]}>
                            <mesh
                              castShadow
                              receiveShadow
                              geometry={nodes.Cylinder767.geometry}
                              material={materials['Small Crane Generic Metal']}
                            />
                            <mesh
                              castShadow
                              receiveShadow
                              geometry={nodes.Cylinder767_1.geometry}
                              material={materials['Small Circle Crane. Yellow']}
                            />
                            <mesh
                              castShadow
                              receiveShadow
                              geometry={nodes.Cylinder767_2.geometry}
                              material={materials['Small Crane Wire']}
                            />
                          </group>
                        </group>
                        <group rotation={[-3.141, 1.569, -1.572]}>
                          <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder039.geometry}
                            material={materials['Small Crane Generic Metal']}
                          />
                          <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder039_1.geometry}
                            material={materials['Small Crane Wire']}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </mesh>
      </group>
      <group position={[-9.762, 0, 2.28]} rotation={[-Math.PI, 0.155, -Math.PI]} scale={0.046}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Small_Crane_Base001.geometry}
          material={materials['Small Circle Crane. Disk Base.001']}
          position={[0, 0.405, 0]}>
          <group position={[0, 3.196, 0]} rotation={[Math.PI / 2, 0, Math.PI]}>
            <group position={[0, 0, 2.67]} rotation={[-Math.PI / 2, 0, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube004.geometry}
                material={materials['Small Circle Crane_Body.001']}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube004_1.geometry}
                material={materials['Small Circle Crane Wheel.001']}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube004_2.geometry}
                material={materials['Small Crane Wire.001']}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube004_3.geometry}
                material={materials['Small Circle Crane. Window.001']}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube004_4.geometry}
                material={materials['Small Crane Generic Metal.001']}
              />
              <group position={[0.082, 2.348, -6.515]} rotation={[0, 1.571, 0]}>
                <group position={[0, -0.072, 4.205]} rotation={[0, -1.571, 0]}>
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube003.geometry}
                    material={materials['Small Circle Crane. Arm.001']}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube003_1.geometry}
                    material={materials['Small Crane Wire.001']}
                  />
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube003_2.geometry}
                    material={materials['Small Crane Generic Metal.001']}
                  />
                  <group position={[-4.304, 49.789, -2.956]} rotation={[0, 1.571, 0]}>
                    <group position={[0, 0, 1.844]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder003.geometry}
                        material={materials['Small Circle Crane. Arm.001']}
                      />
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder003_1.geometry}
                        material={materials['Small Crane Generic Metal.001']}
                      />
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cylinder003_2.geometry}
                        material={materials['Small Crane Wire.001']}
                      />
                    </group>
                    <group position={[0.016, -3.751, -6.299]} rotation={[-Math.PI, 1.571, 0]}>
                      <group position={[6.307, 4.05, 0]} rotation={[Math.PI, 0, 0]}>
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes.Cube005.geometry}
                          material={materials['Small Circle Crane. Yellow.001']}
                        />
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes.Cube005_1.geometry}
                          material={materials['Small Crane Generic Metal.001']}
                        />
                        <mesh
                          castShadow
                          receiveShadow
                          geometry={nodes.Cube005_2.geometry}
                          material={materials['Small Crane Wire.001']}
                        />
                      </group>
                    </group>
                  </group>
                  <group position={[-4.307, 52.615, -0.588]} rotation={[0, Math.PI / 2, 0]}>
                    <group rotation={[0, -Math.PI / 2, 0]}>
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube002.geometry}
                        material={materials['Small Circle Crane. Little Arm.001']}
                      />
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube002_1.geometry}
                        material={materials['Small Crane Generic Metal.001']}
                      />
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={nodes.Cube002_2.geometry}
                        material={materials['Small Crane Wire.001']}
                      />
                      <group position={[0.001, -0.561, -13.802]} rotation={[0, 1.571, 0]}>
                        <group position={[0, -3.993, -1.94]} rotation={[-Math.PI, 1.571, 0]}>
                          <group position={[1.94, 0, 0]} rotation={[0, -0.004, -1.571]}>
                            <mesh
                              castShadow
                              receiveShadow
                              geometry={nodes.Cylinder001.geometry}
                              material={materials['Small Crane Generic Metal.001']}
                            />
                            <mesh
                              castShadow
                              receiveShadow
                              geometry={nodes.Cylinder001_1.geometry}
                              material={materials['Small Circle Crane. Yellow.001']}
                            />
                            <mesh
                              castShadow
                              receiveShadow
                              geometry={nodes.Cylinder001_2.geometry}
                              material={materials['Small Crane Wire.001']}
                            />
                          </group>
                        </group>
                        <group rotation={[-3.141, 1.569, -1.572]}>
                          <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder002.geometry}
                            material={materials['Small Crane Generic Metal.001']}
                          />
                          <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Cylinder002_1.geometry}
                            material={materials['Small Crane Wire.001']}
                          />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </mesh>
      </group>
      <group position={[-9.226, 0, -3.212]} rotation={[Math.PI, -1.073, Math.PI]} scale={0.06}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02001.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02002.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02003.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02004.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02005.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02006.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02007.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02008.geometry}
          material={nodes.Apartment_Buildings02008.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02009.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02010.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02011.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02012.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02013.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02014.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02015.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02016.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02017.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02018.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02019.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02020.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02021.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02022.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02023.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02024.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02025.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02026.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02027.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02028.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02029.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02030.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02031.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02032.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02033.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02034.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02035.geometry}
          material={nodes.Apartment_Buildings02035.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02036.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02037.geometry}
          material={nodes.Apartment_Buildings02037.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02038.geometry}
          material={materials.StoneTile}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02039.geometry}
          material={materials._White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02040.geometry}
          material={materials.StoneTile}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02041.geometry}
          material={materials.StoneTile}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02042.geometry}
          material={materials._White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02043.geometry}
          material={nodes.Apartment_Buildings02043.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02044.geometry}
          material={materials._White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02045.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02046.geometry}
          material={materials.Curtain}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02047.geometry}
          material={materials.StoneTile}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02048.geometry}
          material={materials.StoneTile}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02049.geometry}
          material={materials.StoneTile}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02050.geometry}
          material={materials._White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02051.geometry}
          material={materials.StoneTile}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02052.geometry}
          material={materials.StoneTile}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02053.geometry}
          material={materials._White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02054.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02055.geometry}
          material={materials._White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02056.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02057.geometry}
          material={materials.Curtain}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02059.geometry}
          material={materials.StoneTile}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02060.geometry}
          material={materials.StoneTile}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02061.geometry}
          material={materials.aluminum2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02062.geometry}
          material={materials['glass.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02063.geometry}
          material={materials.aluminum2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02064.geometry}
          material={materials['glass.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02065.geometry}
          material={materials.aluminum2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02066.geometry}
          material={materials['glass.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02068.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02069.geometry}
          material={materials._White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02070.geometry}
          material={materials._White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02071.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02072.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02073.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02074.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02075.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02076.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02077.geometry}
          material={materials.StoneTile}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02078.geometry}
          material={materials.StoneTile}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02079.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02080.geometry}
          material={materials._White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02081.geometry}
          material={materials._White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02082.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02083.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02084.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02085.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02086.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02087.geometry}
          material={materials.StoneTile}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02088.geometry}
          material={materials.StoneTile}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02089.geometry}
          material={materials.StoneTile}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02090.geometry}
          material={materials._White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02091.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02092.geometry}
          material={materials._White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02093.geometry}
          material={nodes.Apartment_Buildings02093.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02094.geometry}
          material={materials._White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02095.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02096.geometry}
          material={materials._White}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02097.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02098.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02099.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02100.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02101.geometry}
          material={nodes.Apartment_Buildings02101.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02102.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02103.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02104.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02105.geometry}
          material={materials._Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Apartment_Buildings02106.geometry}
          material={nodes.Apartment_Buildings02106.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PivotDoor031.geometry}
          material={materials.aluminum2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PivotDoor031_1.geometry}
          material={materials['glass.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RailClone007.geometry}
          material={materials.aluminum2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RailClone007_1.geometry}
          material={materials['glass.001']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/Initial_Timer.glb')